# Generated by Django 4.2.4 on 2024-07-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Doktorning ismi')),
                ('image', models.ImageField(upload_to='', verbose_name='Doktor surati')),
                ('min_skill', models.CharField(max_length=255, verbose_name='Mutahasisligi haqida qisqacha')),
                ('max_skill', models.TextField(verbose_name="Doktor haqida to'liq ma'lumotlar")),
                ('price', models.IntegerField(verbose_name="Bir marotabalik ko'rik narxi ($ da)")),
                ('sertificat1', models.ImageField(upload_to='', verbose_name='1-sertifikat')),
                ('sertificat2', models.ImageField(upload_to='', verbose_name='2-sertifikat')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Doktor yuklangan sana')),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktorlar',
            },
        ),
    ]
