# Generated by Django 4.2.4 on 2024-07-18 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='staj',
            field=models.IntegerField(default=0, verbose_name='Doktorning staji'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doktor',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Doktorning to'liq ismi"),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='price',
            field=models.IntegerField(verbose_name="Bir marotabalik ko'rik narxi '$ da'"),
        ),
    ]
