# Generated by Django 4.2.4 on 2024-07-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_doktor_staj_alter_doktor_name_alter_doktor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doktor',
            name='staj',
        ),
    ]
