# Generated by Django 4.2.4 on 2024-07-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_doktor_chiqish_doktor_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Doktorning to'liq ismi")),
                ('price', models.IntegerField(default=0, verbose_name="Bir marotabalik ko'rik narxi '$ da'")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Doktor yuklangan sana')),
                ('chiqish', models.BooleanField(default=True, verbose_name='Ekranga chiqsinmi?')),
                ('group', models.CharField(choices=[('narkomaniya', 'narkomaniya'), ('reablitatsiya', 'reablitatsiya'), ('alkogolizm', 'alkogolizm'), ('kodirovaniya', 'kodirovaniya')], default='alkogolizm', max_length=100)),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('xirurg', 'xirurg'), ('kardiolog', 'kardiolog'), ('psixolog', 'psixolog')], default='psixolog', max_length=100),
        ),
    ]
