# Generated by Django 4.2.4 on 2024-07-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_xizmat_alter_doktor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('kardiolog', 'kardiolog'), ('psixolog', 'psixolog'), ('xirurg', 'xirurg')], default='psixolog', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('narkomaniya', 'narkomaniya'), ('alkogolizm', 'alkogolizm'), ('kodirovaniya', 'kodirovaniya'), ('reablitatsiya', 'reablitatsiya')], default='alkogolizm', max_length=100),
        ),
    ]
