# Generated by Django 4.2.4 on 2024-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_doktor_group_alter_xizmat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('reablitatsiya', 'reablitatsiya'), ('alkogolizm', 'alkogolizm'), ('kodirovaniya', 'kodirovaniya'), ('narkomaniya', 'narkomaniya')], default='alkogolizm', max_length=100),
        ),
    ]
