# Generated by Django 4.2.4 on 2024-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_xizmat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('psixolog', 'psixolog'), ('xirurg', 'xirurg'), ('kardiolog', 'kardiolog')], default='psixolog', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Xizmat yuklangan sana'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('narkomaniya', 'narkomaniya'), ('kodirovaniya', 'kodirovaniya'), ('alkogolizm', 'alkogolizm'), ('reablitatsiya', 'reablitatsiya')], default='alkogolizm', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Xizmat nomi'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='price',
            field=models.IntegerField(default=0, verbose_name="Bir marotabalik xizmat narxi '$ da'"),
        ),
    ]
