# Generated by Django 4.2.4 on 2024-08-02 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_galery_alter_doktor_group_alter_xizmat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Doktor yuklangan sana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('psixolog', 'psixolog'), ('xirurg', 'xirurg'), ('kardiolog', 'kardiolog')], default='psixolog', max_length=100),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(default='static/img/foto-klinika.png', null=True, upload_to='gallery', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='title',
            field=models.CharField(default='Klinika', max_length=120, verbose_name='Bu qayerning surati'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('reablitatsiya', 'reablitatsiya'), ('kodirovaniya', 'kodirovaniya'), ('alkogolizm', 'alkogolizm'), ('narkomaniya', 'narkomaniya')], default='alkogolizm', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], default='uz', max_length=100),
        ),
    ]
