# Generated by Django 4.2.4 on 2024-08-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_galery_date_alter_doktor_group_alter_galery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('xirurg', 'xirurg'), ('psixolog', 'psixolog'), ('kardiolog', 'kardiolog')], default='psixolog', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('reablitatsiya', 'reablitatsiya'), ('kodirovaniya', 'kodirovaniya'), ('narkomaniya', 'narkomaniya'), ('alkogolizm', 'alkogolizm')], default='alkogolizm', max_length=100),
        ),
    ]
