# Generated by Django 4.2.4 on 2024-08-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_doktor_group_alter_xizmat_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xizmat',
            name='staj',
        ),
        migrations.AddField(
            model_name='doktor',
            name='staj',
            field=models.IntegerField(default=1, verbose_name='Doktor ish staji'),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('psixolog', 'psixolog'), ('kardiolog', 'kardiolog'), ('xirurg', 'xirurg')], default='psixolog', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('narkomaniya', 'narkomaniya'), ('reablitatsiya', 'reablitatsiya'), ('alkogolizm', 'alkogolizm'), ('kodirovaniya', 'kodirovaniya')], default='alkogolizm', max_length=100),
        ),
    ]
