# Generated by Django 4.2.4 on 2024-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_xizmat_staj_doktor_staj_alter_doktor_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('psixolog', 'psixolog'), ('xirurg', 'xirurg'), ('kardiolog', 'kardiolog')], default='psixolog', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('kodirovaniya', 'kodirovaniya'), ('narkomaniya', 'narkomaniya'), ('alkogolizm', 'alkogolizm'), ('reablitatsiya', 'reablitatsiya')], default='alkogolizm', max_length=100),
        ),
    ]
