# Generated by Django 4.2.4 on 2024-08-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_doktor_group_alter_xizmat_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Xizmat guruhi')),
            ],
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('xirurg', 'xirurg'), ('psixolog', 'psixolog'), ('kardiolog', 'kardiolog')], default='psixolog', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('reablitatsiya', 'reablitatsiya'), ('narkomaniya', 'narkomaniya'), ('kodirovaniya', 'kodirovaniya'), ('alkogolizm', 'alkogolizm')], default='alkogolizm', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz')], default='uz', max_length=100),
        ),
        migrations.AddField(
            model_name='xizmat',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
