# Generated by Django 4.2.4 on 2024-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_doktor_group_alter_xizmat_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('alkogolizm', 'alkogolizm'), ('narkomaniya', 'narkomaniya'), ('reablitatsiya', 'reablitatsiya'), ('kodirovaniya', 'kodirovaniya')], default='alkogolizm', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz')], default='uz', max_length=100),
        ),
    ]
