# Generated by Django 4.2.4 on 2024-08-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_xizmat_group_alter_xizmat_group_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('kardiolog', 'kardiolog'), ('psixolog', 'psixolog'), ('xirurg', 'xirurg')], default='psixolog', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('stamatologiya', 'stamatologiya'), ('okulistika', 'okulistika'), ('travmatalogiya', 'travmatalogiya')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], default='uz', max_length=100),
        ),
    ]
