# Generated by Django 4.2.4 on 2024-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_doktor_group_alter_xizmat_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('travmatalogiya', 'travmatalogiya'), ('stamatologiya', 'stamatologiya'), ('okulistika', 'okulistika')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='galery',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Rasm yuklangan sana'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('travmatalogiya', 'travmatalogiya'), ('stamatologiya', 'stamatologiya'), ('okulistika', 'okulistika')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz')], default='uz', max_length=100),
        ),
    ]
