# Generated by Django 4.2.4 on 2024-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_doktor_group_alter_galery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('okulistika', 'okulistika'), ('travmatalogiya', 'travmatalogiya'), ('stamatologiya', 'stamatologiya')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('okulistika', 'okulistika'), ('travmatalogiya', 'travmatalogiya'), ('stamatologiya', 'stamatologiya')], default='stamatologiya', max_length=100),
        ),
    ]
