# Generated by Django 4.2.4 on 2024-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_doktor_group_alter_xizmat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('okulistika', 'okulistika'), ('stamatologiya', 'stamatologiya'), ('travmatalogiya', 'travmatalogiya')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('okulistika', 'okulistika'), ('stamatologiya', 'stamatologiya'), ('travmatalogiya', 'travmatalogiya')], default='stamatologiya', max_length=100),
        ),
    ]
