# Generated by Django 4.2.4 on 2024-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_doktor_group_lang_alter_doktor_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='sertificat3',
            field=models.ImageField(null=True, upload_to='', verbose_name='3-sertifikat'),
        ),
        migrations.AddField(
            model_name='doktor',
            name='sertificat4',
            field=models.ImageField(null=True, upload_to='', verbose_name='4-sertifikat'),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('stamatologiya', 'stamatologiya'), ('travmatalogiya', 'travmatalogiya'), ('okulistika', 'okulistika')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='sertificat1',
            field=models.ImageField(null=True, upload_to='', verbose_name='1-sertifikat'),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='sertificat2',
            field=models.ImageField(null=True, upload_to='', verbose_name="2-sertifikat (bu va bundan pastdagilarini to'ldirmaslik mumkin)"),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('stamatologiya', 'stamatologiya'), ('travmatalogiya', 'travmatalogiya'), ('okulistika', 'okulistika')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], default='uz', max_length=100),
        ),
    ]
