# Generated by Django 4.2.4 on 2024-09-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_doktor_sertificat3_doktor_sertificat4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('travmatalogiya', 'travmatalogiya'), ('okulistika', 'okulistika'), ('stamatologiya', 'stamatologiya')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='sertificat2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="2-sertifikat (bu va bundan pastdagilarini to'ldirmaslik mumkin)"),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='sertificat3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='3-sertifikat'),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='sertificat4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='4-sertifikat'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group',
            field=models.CharField(choices=[('travmatalogiya', 'travmatalogiya'), ('okulistika', 'okulistika'), ('stamatologiya', 'stamatologiya')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz')], default='uz', max_length=100),
        ),
    ]
