# Generated by Django 4.2.4 on 2024-09-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_doktor_group_alter_doktor_group_lang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xizmat',
            old_name='category',
            new_name='min_group',
        ),
        migrations.RemoveField(
            model_name='xizmat',
            name='group',
        ),
        migrations.AddField(
            model_name='xizmat',
            name='max_group',
            field=models.CharField(choices=[('okulistika', 'okulistika'), ('stamatologiya', 'stamatologiya'), ('travmatalogiya', 'travmatalogiya')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('okulistika', 'okulistika'), ('stamatologiya', 'stamatologiya'), ('travmatalogiya', 'travmatalogiya')], default='stamatologiya', max_length=100),
        ),
    ]
