# Generated by Django 4.2.4 on 2024-09-03 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_category_xizmat_min_group_remove_xizmat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Xizmat yuklangan sana'),
            preserve_default=False,
        ),
    ]
