# Generated by Django 4.2.4 on 2024-09-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_category_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='big_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Katta xizmat guruxi')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Katta xizmat yuklangan sana')),
            ],
        ),
        migrations.CreateModel(
            name='small_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kichik xizmat guruhi')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Kichik xizmat yuklangan sana')),
            ],
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('okulistika', 'okulistika'), ('travmatalogiya', 'travmatalogiya'), ('stamatologiya', 'stamatologiya')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='max_group',
            field=models.ForeignKey(default="yo'q", on_delete=django.db.models.deletion.CASCADE, to='blog.big_category'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='min_group',
            field=models.ForeignKey(default='bor', on_delete=django.db.models.deletion.CASCADE, to='blog.small_category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
