# Generated by Django 4.2.4 on 2024-09-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_big_category_small_category_alter_doktor_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('stamatologiya', 'stamatologiya'), ('okulistika', 'okulistika'), ('travmatalogiya', 'travmatalogiya')], default='stamatologiya', max_length=100),
        ),
    ]
