# Generated by Django 4.2.4 on 2024-09-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_doktor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('travmatalogiya', 'travmatalogiya'), ('okulistika', 'okulistika'), ('stamatologiya', 'stamatologiya')], default='stamatologiya', max_length=100),
        ),
    ]
