# Generated by Django 4.2.4 on 2024-09-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_doktor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='small_category',
            name='bc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.big_category'),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('okulistika', 'okulistika'), ('travmatalogiya', 'travmatalogiya'), ('stamatologiya', 'stamatologiya')], default='stamatologiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz')], default='uz', max_length=100),
        ),
    ]
