# Generated by Django 4.2 on 2025-01-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_big_category_group_lang_alter_doktor_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='group',
            field=models.CharField(choices=[('travmatalogiya', 'travmatalogiya'), ('okulistika', 'okulistika'), ('stamatologiya', 'stamatologiya')], default='stamatologiya', max_length=100),
        ),
    ]
